-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggtVUCOIGOJ5mFliJ
zIy/HLk3lIaixRskhJyuaSb/pGqgCgYIKoZIzj0DAQehRANCAARlmStgHQJl5fZg
8/00xk73KL28JwW+aNApLW5YTNhnAFKSmLCQfEBXrabSRh16LexoJVI7g9RZ921n
oQZrX43x
-----END PRIVATE KEY-----