# Generated by Django 2.1.15 on 2020-03-16 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0007_auto_20200310_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_inquiry', models.DateTimeField()),
                ('renter_brand', models.CharField(max_length=50)),
                ('sent_text_date', models.DateTimeField()),
                ('sent_email_date', models.DateTimeField()),
                ('filled_out_form', models.BooleanField(default=False)),
                ('made_appointment', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Company')),
            ],
        ),
    ]
