# Generated by Django 2.1.15 on 2020-03-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200319_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Company'),
        ),
    ]
