# Generated by Django 2.1.15 on 2020-03-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200319_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='sent_email_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sent_text_date',
            field=models.DateTimeField(null=True),
        ),
    ]
