# Generated by Django 2.1.15 on 2020-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20200320_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='renter_brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
