# Generated by Django 2.0.2 on 2018-02-19 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('proposed_jobs', models.BooleanField(default=False)),
                ('pending_payments', models.BooleanField(default=False)),
                ('payment_history', models.BooleanField(default=False)),
                ('completed_jobs', models.BooleanField(default=False)),
                ('companies', models.ManyToManyField(through='jobs.Current_Worker', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('approved', models.BooleanField(default=False)),
                ('document_link', models.FileField(upload_to=jobs.models.Job.generate_filename)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.House')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('approved', models.BooleanField(default=False)),
                ('document_link', models.FileField(upload_to=jobs.models.Request_Payment.generate_filename)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.House')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.AddField(
            model_name='current_worker',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.House'),
        ),
    ]
