# Generated by Django 2.0.2 on 2018-02-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('document_link', models.CharField(max_length=800)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.House')),
            ],
        ),
    ]
