# Generated by Django 2.0.2 on 2018-02-15 02:21

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=jobs.models.Job.balance, max_digits=8),
        ),
    ]
