# Generated by Django 2.0.4 on 2018-04-15 02:04

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180219_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_list_file',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.House.generate_file_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='document_link',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.Job.generate_file_path),
        ),
        migrations.AlterField(
            model_name='request_payment',
            name='document_link',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.Request_Payment.generate_file_path),
        ),
    ]
