# Generated by Django 2.0.2 on 2018-02-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180208_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_worker',
            old_name='contractor',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='contractors',
            new_name='companies',
        ),
    ]
