# Generated by Django 2.0.2 on 2018-02-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180215_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
