# Generated by Django 2.0.4 on 2018-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180420_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_payment',
            name='requested_by_worker',
            field=models.BooleanField(default=False),
        ),
    ]
