# Generated by Django 2.0.2 on 2018-02-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_request_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='proposed_jobs',
            field=models.BooleanField(default=False),
        ),
    ]
