# Generated by Django 2.0.2 on 2018-02-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180215_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='completed_jobs',
            field=models.BooleanField(default=False),
        ),
    ]
