# Generated by Django 2.0.2 on 2018-02-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_house_proposed_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pending_payments',
            field=models.BooleanField(default=False),
        ),
    ]
