# Generated by Django 2.0.2 on 2018-02-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_house_pending_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='payment_history',
            field=models.BooleanField(default=False),
        ),
    ]
