# Generated by Django 2.0.2 on 2018-02-11 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_house_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_payment',
            name='house',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobs.House'),
        ),
    ]
