# Generated by Django 2.0.2 on 2018-02-11 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_request_payment_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_payment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.House'),
        ),
    ]
