# Generated by Django 2.1.7 on 2020-01-12 15:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0006_auto_20191110_2007'),
        ('customer_register', '0003_auto_20191107_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('lease_begin', models.DateField()),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('customer_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_register.Customer_User')),
            ],
        ),
    ]
