# Generated by Django 2.1.15 on 2020-09-29 17:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_company_disabled_days_created'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='customer_user',
        ),
        migrations.AddField(
            model_name='tenant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Company'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lease_length',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
    ]
