# Generated by Django 2.1.15 on 2020-09-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20200929_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
