# Generated by Django 2.0.2 on 2018-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companyname',
            field=models.CharField(default='Company Name', max_length=250),
        ),
    ]
