# Generated by Django 2.1.7 on 2019-11-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_customer_user'),
        ('customer_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_user',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
