# Generated by Django 2.1.7 on 2019-11-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0002_customer_user_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_user',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
