# Generated by Django 2.1.15 on 2020-03-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0003_auto_20191107_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_user',
            old_name='property',
            new_name='company',
        ),
    ]
