# Generated by Django 2.1.15 on 2020-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0004_auto_20200310_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_user',
            name='customer_type',
            field=models.CharField(choices=[('HF', 'House Flipper'), ('PM', 'Property Manager'), ('MW', 'Medical Worker')], default='HF', max_length=100),
        ),
    ]
