# Generated by Django 2.1.15 on 2020-04-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0005_auto_20200312_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_user',
            name='company',
        ),
    ]
