# Generated by Django 2.1.15 on 2020-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0007_customer_user_wants_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_user',
            name='ios_push_notification_token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
