# Generated by Django 2.1.15 on 2020-09-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0008_customer_user_ios_push_notification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_User_Push_Notification_Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notification_token', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('', 'Mobile Device Type'), ('iOS', 'iOS'), ('Android', 'Android')], default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_user',
            name='ios_push_notification_token',
        ),
        migrations.AddField(
            model_name='customer_user_push_notification_tokens',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_register.Customer_User'),
        ),
    ]
