# Generated by Django 2.1.7 on 2019-10-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='task_id',
            new_name='apply_task_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_task_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
