# Generated by Django 2.1.7 on 2019-11-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0003_auto_20191107_1542'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='apartment_complex_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_register.Customer_User'),
        ),
    ]
