# Generated by Django 2.1.15 on 2020-03-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20200311_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Medical',
            fields=[
                ('appointment_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.Appointment_Base')),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('test_type', models.CharField(choices=[('', 'Test Type'), ('Calcium blood test', 'Calcium blood test'), ('Folate test', 'Folate test'), ('D-dimer test', 'D-dimer test'), ('Other', 'Other')], default='', max_length=100)),
                ('gender', models.CharField(choices=[('', 'Gender'), ('M', 'Male'), ('F', 'Female')], default='', max_length=100)),
            ],
            bases=('appointments.appointment_base',),
        ),
    ]
