# Generated by Django 2.1.7 on 2019-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_apartment_complex_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apartment_complex_name',
            field=models.CharField(blank=True, default=None, editable=False, max_length=128),
        ),
    ]
