# Generated by Django 2.1.15 on 2020-03-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_medical',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
