# Generated by Django 2.1.15 on 2020-03-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_medical_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_medical',
            name='test_type',
            field=models.CharField(choices=[('', 'Test Type'), ('Comprehensive Metabolic Panel', 'Comprehensive Metabolic Panel'), ('Basic Metabolic Panel', 'Basic Metabolic Panel'), ('Lipid Panel', 'Lipid Panel'), ('Lipid Panel Plus', 'Lipid Panel Plus'), ('Liver Panel Plus', 'Liver Panel Plus'), ('General Chemistry 6', 'General Chemistry 6'), ('General Chemistry 13', 'General Chemistry 13'), ('Electrolyte Panel', 'Electrolyte Panel'), ('Kidney Check', 'Kidney Check'), ('Renal Function Panel', 'Renal Function Panel'), ('MetLyte 8 Panel', 'MetLyte 8 Panel'), ('Hepatic Function Panel', 'Hepatic Function Panel'), ('Basic Metabolic Panel Plus', 'Basic Metabolic Panel Plus'), ('MetLyte Plus CRP', 'MetLyte Plus CRP'), ('Biochemistry Panel Plus', 'Biochemistry Panel Plus'), ('MetLac 12 Panel', 'MetLac 12 Panel')], default='', max_length=100),
        ),
    ]
