# Generated by Django 2.1.15 on 2020-07-13 01:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20200712_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_medical',
            name='test_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'Test Type'), ('COVID 19 Antibody IgG And IgM', 'COVID 19 Antibody IgG And IgM'), ('Mono', 'Mono'), ('Influenza A And B', 'Influenza A And B'), ('Strep Screen', 'Strep Screen'), ('CMP', 'CMP'), ('BMP', 'BMP'), ('Lipid Profile', 'Lipid Profile'), ('Liver Profile', 'Liver Profile'), ('Chem 13', 'Chem 13'), ('Glyco Hemoglobin', 'Glyco Hemoglobin'), ('Microalbumin Urine', 'Microalbumin Urine'), ('Urinalysis', 'Urinalysis'), ('Pregnancy Test (Qualitative)', 'Pregnancy Test (Qualitative)'), ('CBC With Diff', 'CBC With Diff')], default=None, max_length=200),
        ),
    ]
