# Generated by Django 2.1.15 on 2020-07-14 01:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20200713_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_medical',
            name='test_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CMP', 'CMP'), ('BMP', 'BMP'), ('Liver Profile', 'Liver Profile'), ('Lipid Profile', 'Lipid Profile'), ('Chem 13', 'Chem 13'), ('Glyco Hemoglobin', 'Glyco Hemoglobin'), ('Microalbumin Urine', 'Microalbumin Urine'), ('Urinalysis', 'Urinalysis'), ('CBC', 'CBC'), ('CBC With Diff', 'CBC With Diff'), ('CoVID19 Antibody IgG / IgM', 'CoVID19 Antibody IgG / IgM'), ('Mono', 'Mono'), ('Influenza A & B', 'Influenza A & B'), ('Strep Screen', 'Strep Screen'), ('Pregnancy Test Qualitative', 'Pregnancy Test Qualitative')], default=None, max_length=196),
        ),
    ]
