# Generated by Django 2.1.15 on 2020-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20200713_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_medical',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
