# Generated by Django 2.1.7 on 2019-11-06 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='customer_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer_register.Customer_User'),
            preserve_default=False,
        ),
    ]
