# Generated by Django 2.1.7 on 2019-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
