# Generated by Django 2.1.7 on 2019-11-11 01:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_days_of_the_week_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hours_of_the_day_enabled',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=None, max_length=13),
        ),
    ]
