# Generated by Django 2.1.15 on 2020-03-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('customer_register', '0004_auto_20200310_1953'),
        ('property', '0006_auto_20191110_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Company',
        ),
    ]
