# Generated by Django 2.1.15 on 2020-06-17 23:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200407_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_respond_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_respond_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
