# Generated by Django 2.1.15 on 2020-06-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200617_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='auto_respond_text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
