# Generated by Django 2.1.15 on 2020-07-16 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20200627_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='disabled_datetime_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='company',
            name='disabled_datetime_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
