# Generated by Django 2.1.15 on 2020-07-16 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200716_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Disabled_Datetimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_datetime_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_datetime_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Company')),
            ],
        ),
    ]
