# Generated by Django 2.1.15 on 2020-07-16 20:23

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_company_disabled_datetimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_disabled_datetimes',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='US/Eastern', editable=False),
        ),
    ]
