# Generated by Django 2.1.15 on 2020-07-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_company_disabled_datetimes_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_disabled_datetimes',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
