# Generated by Django 2.1.15 on 2020-07-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_company_allow_same_day_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_disabled_days',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
